In [7]:
import numpy as np

# Start glyph
target_vector = np.array([0.29737395449823, -0.94155024712979, 0.15827780424279])
start_vector = np.array([0.18983879552606, -0.9818152737217, 0])

glyph1 = np.array([0.39831700267993, -0.85296865578697, 0.3373248250886])
glyph2 = np.array([0.18983879552606, -0.9818152737217, 0])

print(np.dot(glyph1, target_vector))
print(np.dot(glyph2, target_vector))


0.9749529835126061
0.9808815269512343


In [9]:
# Glyph 2

candidate1 = np.array([0.2578876309611, -0.93826595916962, 0.23054491896546])
candidate2 = np.array([0.23756216274032, -0.93235010089966, 0.27255734843613])
candidate3 = np.array([0.30839991656099, -0.92406741433044, 0.22580723026029])
candidate4 = np.array([0.39831700267993, -0.85296865578697, 0.3373248250886]) # identity

print(np.dot(candidate1, target_vector))
print(np.dot(candidate2, target_vector))
print(np.dot(candidate3, target_vector))
print(np.dot(candidate4, target_vector))

0.9966037539178926
0.9916390463275082
0.9975062776698224
0.9749529835126061


In [16]:
# Glyph 3

candidate1 = np.array([0.3045462890841, -0.92647744481758, 0.22111332399787])
candidate2 = np.array([0.29824853476143, -0.92837467939717, 0.2217391850054])
candidate3 = np.array([0.2943935212275, -0.93071186166462, 0.21704350996069])
candidate4 = np.array([0.30839991656099, -0.92406741433044, 0.22580723026029]) # identity

print(np.dot(candidate1, target_vector))
print(np.dot(candidate2, target_vector))
print(np.dot(candidate3, target_vector))
print(np.dot(candidate4, target_vector))

0.9978865328520762
0.9978991463379947
0.9982101191247563
0.9975062776698224


In [8]:
right_corner = np.array([0.57735021142964, -0.57735041155694, 0.57735018458227])
top_corner = np.array([0.52573107107952, -0.8506508337159, 1.4848270733249e-07])
left_corner = np.array([1.7533007652899e-07, -0.93417235727245, 0.35682209419822])

top_fr_center = np.array([0.41856259955263, -0.8591652476213, 0.29434746055568])
right_fr_center = np.array([0.42642857325082, -0.82398946646319, 0.37309520376571])
left_fr_center = np.array([0.34830020365025, -0.87227545436196, 0.3432528220639])

sub_side_up = glyph1 - top_fr_center
sub_side_r = glyph1 - right_fr_center
sub_side_l = glyph1 - left_fr_center
print(sub_side_up, sub_side_r, sub_side_l)

[-0.0202456   0.00619659  0.04297736] [-0.02811157 -0.02897919 -0.03577038] [ 0.0500168  0.0193068 -0.005928 ]


In [9]:
target_vector = np.array([0.29737395449823, -0.94155024712979, 0.15827780424279])

vec1 = top_fr_center - left_fr_center
vec2 =  top_fr_center - right_fr_center

plane = np.cross(vec1, vec2)
print(plane)
# plane is -0.00275268(x - 0.52573107107952) + 0.00591769(y + -0.8506508337159) + -0.00236841(z - 1.4848270733249e-07) = 0   <- this is an approximation, why would I do this, I can calculate the exact tangent plane

projT = target_vector - np.dot((np.dot(target_vector, plane)/np.linalg.norm(plane, 2)**2), plane)
print(projT)
proj_rc = right_corner - np.dot((np.dot(right_corner, plane)/np.linalg.norm(plane, 2)**2), plane)
proj_tc = top_corner - np.dot((np.dot(top_corner, plane)/np.linalg.norm(plane, 2)**2), plane)
proj_lc = left_corner - np.dot((np.dot(left_corner, plane)/np.linalg.norm(plane, 2)**2), plane)
print(proj_rc, proj_tc, proj_lc)

[-0.00275268  0.00591769 -0.00236841]
[-0.0889409  -0.11105417 -0.17410767]
[0.21341976 0.20502388 0.26422426] [ 0.15564407 -0.05504123 -0.31842288] [-0.36393027 -0.15179806  0.04369617]


----------------

In [2]:
# Glyph 1/7

import numpy as np
from sympy.solvers import solve
from sympy import Symbol

# plane is 0.39831700267993(x-0.39831700267993) - 0.85296865578697(y + 0.85296865578697) + 0.3373248250886(z - 0.3373248250886) = 0
target_vector = np.array([0.29737395449823, -0.94155024712979, 0.15827780424279])

t = Symbol('t')
SV_bottom_left = np.array([0.022309014248043, -0.94783788183708, -0.31797115850007])
t1 = solve(0.18983879552606*(SV_bottom_left[0]*t - 0.18983879552606) - 0.9818152737217*(SV_bottom_left[1]*t + 0.9818152737217) + 0*(SV_bottom_left[2]*t - 0), t)
#print(t1)
bottom_left_corner = SV_bottom_left * t1

SV_adj_bottom_left = np.array([0.045350385200006, -0.95979326644615, -0.27702026685216])
t2 = solve(0.18983879552606*(SV_adj_bottom_left[0]*t - 0.18983879552606) - 0.9818152737217*(SV_adj_bottom_left[1]*t + 0.9818152737217) + 0*(SV_adj_bottom_left[2]*t - 0), t)
#print(t2)
adj_bottom_left_corner = SV_adj_bottom_left * t2

SV_up_adj_bottom_left = np.array([0.091047784910431, -0.95623310145537, -0.27808012612187])
t3 = solve(0.18983879552606*(SV_up_adj_bottom_left[0]*t - 0.18983879552606) - 0.9818152737217*(SV_up_adj_bottom_left[1]*t + 0.9818152737217) + 0*(SV_up_adj_bottom_left[2]*t - 0), t)
#print(t3)
up_adj_bottom_left_corner = SV_up_adj_bottom_left * t3

SV_down_adj_bottom_left = np.array([0.022882799194568, -0.9722161489491, -0.23296381097416])
t4 = solve(0.18983879552606*(SV_down_adj_bottom_left[0]*t - 0.18983879552606) - 0.9818152737217*(SV_down_adj_bottom_left[1]*t + 0.9818152737217) + 0*(SV_down_adj_bottom_left[2]*t - 0), t)
#print(t4)
down_adj_bottom_left_corner = SV_down_adj_bottom_left * t4

test = np.array([0.16154248563038, -0.95849069268593, -0.23494598819901])
t5 = solve(0.18983879552606*(test[0]*t - 0.18983879552606) - 0.9818152737217*(test[1]*t + 0.9818152737217) + 0*(test[2]*t - 0), t)
#print(t5)
test_1 = test * t5

test_2 = test_1 - up_adj_bottom_left_corner
print(test_2)
#print(np.linalg.norm(test_2.astype(float)))

first_diag = []
up_right_interval = up_adj_bottom_left_corner - bottom_left_corner
print(up_right_interval)
#print(np.linalg.norm(up_right_interval.astype(float)))
#print("percent: ", abs(np.linalg.norm(up_right_interval.astype(float)) - np.linalg.norm(test_2.astype(float))) / np.linalg.norm(test_2.astype(float)))
for i in range(8):
    first_diag.append(bottom_left_corner + test_2*i)
diag_1 = np.array(first_diag)
#print(diag_1)
#print(adj_bottom_left_corner)

up_diag_interval = adj_bottom_left_corner - bottom_left_corner
diag_2 = diag_1[:-1] + up_diag_interval
#print(diag_2)
#print(adj_bottom_left_corner)

right_interval = down_adj_bottom_left_corner - diag_2[0]

diags = [diag_1, diag_2]
for i in range(13):
    if i % 2 == 0:
        diags.append(diags[i+1] + right_interval)
    else:
        diags.append(diags[i+1][:-1] + up_diag_interval)

# print(diags)  # You have no idea how long getting here took

min_dot_cord = [0, 0]
min_dot = 10
for i in range(len(diags)):
    diags[i] = diags[i].astype(float)
    for j in range(len(diags[i])):
        current_dot = abs(1 - np.dot(target_vector, diags[i][j] / np.linalg.norm(diags[i][j])))
        print(diags[i][j] / np.linalg.norm(diags[i][j]))
        if current_dot < min_dot:
            min_dot = current_dot
            min_dot_cord = (i, j)
print(min_dot_cord)
print(diags[min_dot_cord[0]][min_dot_cord[1]] / np.linalg.norm(diags[min_dot_cord[0]][min_dot_cord[1]]))
print(diags[4][0] / np.linalg.norm(diags[4][0]))
print(min_dot)

[0.0710170694885413 0.0137314984746473 0.0490579691898740]
[0.0713613795435393 0.0137980725114117 0.0492958155582446]
[ 0.02230901 -0.94783788 -0.31797116]
[ 0.09071003 -0.95620667 -0.27828132]
[ 0.16119786 -0.95849563 -0.23516245]
[ 0.2323667  -0.95403751 -0.18925685]
[ 0.3026553  -0.94254719 -0.1414375 ]
[ 0.37050628 -0.92418926 -0.09273242]
[ 0.43453373 -0.89956949 -0.04421724]
[ 0.49365871 -0.8696502   0.0030988 ]
[ 0.04535039 -0.95979327 -0.27702027]
[ 0.11508472 -0.96519241 -0.2348598 ]
[ 0.18627928 -0.96401208 -0.18968589]
[ 0.25741713 -0.95576549 -0.14229808]
[ 0.32690128 -0.94040341 -0.09368558]
[ 0.39322642 -0.9183433  -0.04492847]
[ 0.45513749 -0.89041639  0.00291889]
[ 0.0228828  -0.97221615 -0.23296381]
[ 0.0927293  -0.9774925  -0.18949851]
[ 0.16413722 -0.97597332 -0.14330053]
[ 0.23556782 -0.96718046 -0.09523524]
[ 0.30540032 -0.95109592 -0.04633785]
[ 0.37210869 -0.92818633  0.00229377]
[ 0.43442338 -0.89934105  0.04961862]
[ 0.04634983 -0.98094538 -0.18867394]
[ 0.1171

In [3]:
# Glyph 2/7

t = Symbol('t')
SV_bottom_left = np.array([0.28391784830449, -0.95348081729694, 0.10131626947785])
t1 = solve(0.18983879552606*(SV_bottom_left[0]*t - 0.18983879552606) - 0.9818152737217*(SV_bottom_left[1]*t + 0.9818152737217) + 0*(SV_bottom_left[2]*t - 0), t)
#print(t1)
bottom_left_corner = SV_bottom_left * t1

SV_adj_bottom_left = np.array([0.28655452419658, -0.95205127828681, 0.10716747722573])
t2 = solve(0.18983879552606*(SV_adj_bottom_left[0]*t - 0.18983879552606) - 0.9818152737217*(SV_adj_bottom_left[1]*t + 0.9818152737217) + 0*(SV_adj_bottom_left[2]*t - 0), t)
#print(t2)
adj_bottom_left_corner = SV_adj_bottom_left * t2

SV_up_adj_bottom_left = np.array([0.29216636714988, -0.9503538781119, 0.10708090522646])
t3 = solve(0.18983879552606*(SV_up_adj_bottom_left[0]*t - 0.18983879552606) - 0.9818152737217*(SV_up_adj_bottom_left[1]*t + 0.9818152737217) + 0*(SV_up_adj_bottom_left[2]*t - 0), t)
#print(t3)
up_adj_bottom_left_corner = SV_up_adj_bottom_left * t3

SV_down_adj_bottom_left = np.array([0.2835555020963, -0.95226395065473, 0.11309131493778])
t4 = solve(0.18983879552606*(SV_down_adj_bottom_left[0]*t - 0.18983879552606) - 0.9818152737217*(SV_down_adj_bottom_left[1]*t + 0.9818152737217) + 0*(SV_down_adj_bottom_left[2]*t - 0), t)
#print(t4)
down_adj_bottom_left_corner = SV_down_adj_bottom_left * t4

first_diag = []
up_right_interval = up_adj_bottom_left_corner - bottom_left_corner
for i in range(8):
    first_diag.append(bottom_left_corner + up_right_interval*i)
diag_1 = np.array(first_diag)

up_diag_interval = adj_bottom_left_corner - bottom_left_corner
diag_2 = diag_1[:-1] + up_diag_interval

right_interval = down_adj_bottom_left_corner - diag_2[0]

diags = [diag_1, diag_2]
for i in range(13):
    if i % 2 == 0:
        diags.append(diags[i+1] + right_interval)
    else:
        diags.append(diags[i+1][:-1] + up_diag_interval)

min_dot_cord = [0, 0]
min_dot = 10
for i in range(len(diags)):
    diags[i] = diags[i].astype(float)
    for j in range(len(diags[i])):
        current_dot = abs(1 - np.dot(target_vector, diags[i][j] / np.linalg.norm(diags[i][j])))
        #print(diags[i][j] / np.linalg.norm(diags[i][j]))
        if current_dot < min_dot:
            min_dot = current_dot
            min_dot_cord = (i, j)
print(min_dot_cord)
print(diags[min_dot_cord[0]][min_dot_cord[1]] / np.linalg.norm(diags[min_dot_cord[0]][min_dot_cord[1]]))
print(min_dot)

(8, 2)
[ 0.2984257  -0.94104274  0.15931308]
1.217770619565961e-06


In [4]:
# Glyph 3/7

t = Symbol('t')
SV_bottom_left = np.array([0.29623778153661, -0.94256766506046, 0.15430286313851])
t1 = solve(0.18983879552606*(SV_bottom_left[0]*t - 0.18983879552606) - 0.9818152737217*(SV_bottom_left[1]*t + 0.9818152737217) + 0*(SV_bottom_left[2]*t - 0), t)
#print(t1)
bottom_left_corner = SV_bottom_left * t1

SV_adj_bottom_left = np.array([0.2965507417259, -0.94235234500546, 0.1550152103651])
t2 = solve(0.18983879552606*(SV_adj_bottom_left[0]*t - 0.18983879552606) - 0.9818152737217*(SV_adj_bottom_left[1]*t + 0.9818152737217) + 0*(SV_adj_bottom_left[2]*t - 0), t)
#print(t2)
adj_bottom_left_corner = SV_adj_bottom_left * t2

SV_up_adj_bottom_left = np.array([0.29724407884285, -0.94213659883565, 0.15499866685641])
t3 = solve(0.18983879552606*(SV_up_adj_bottom_left[0]*t - 0.18983879552606) - 0.9818152737217*(SV_up_adj_bottom_left[1]*t + 0.9818152737217) + 0*(SV_up_adj_bottom_left[2]*t - 0), t)
#print(t3)
up_adj_bottom_left_corner = SV_up_adj_bottom_left * t3

SV_down_adj_bottom_left = np.array([0.29616998679182, -0.94235195613243, 0.1557437950517])
t4 = solve(0.18983879552606*(SV_down_adj_bottom_left[0]*t - 0.18983879552606) - 0.9818152737217*(SV_down_adj_bottom_left[1]*t + 0.9818152737217) + 0*(SV_down_adj_bottom_left[2]*t - 0), t)
#print(t4)
down_adj_bottom_left_corner = SV_down_adj_bottom_left * t4

first_diag = []
up_right_interval = up_adj_bottom_left_corner - bottom_left_corner
for i in range(8):
    first_diag.append(bottom_left_corner + up_right_interval*i)
diag_1 = np.array(first_diag)

up_diag_interval = adj_bottom_left_corner - bottom_left_corner
diag_2 = diag_1[:-1] + up_diag_interval

right_interval = down_adj_bottom_left_corner - diag_2[0]

diags = [diag_1, diag_2]
for i in range(13):
    if i % 2 == 0:
        diags.append(diags[i+1] + right_interval)
    else:
        diags.append(diags[i+1][:-1] + up_diag_interval)

min_dot_cord = [0, 0]
min_dot = 10
for i in range(len(diags)):
    diags[i] = diags[i].astype(float)
    for j in range(len(diags[i])):
        current_dot = abs(1 - np.dot(target_vector, diags[i][j] / np.linalg.norm(diags[i][j])))
        #print(diags[i][j] / np.linalg.norm(diags[i][j]))
        if current_dot < min_dot:
            min_dot = current_dot
            min_dot_cord = (i, j)
print(min_dot_cord)
print(diags[min_dot_cord[0]][min_dot_cord[1]] / np.linalg.norm(diags[min_dot_cord[0]][min_dot_cord[1]]))
print(min_dot)

(5, 1)
[ 0.29741857 -0.94148378  0.15858903]
5.163549032793924e-08


In [5]:
# Glyph 4/7

t = Symbol('t')
SV_bottom_left = np.array([0.29769103335384, -0.94129276679002, 0.1592104765696])
t1 = solve(0.18983879552606*(SV_bottom_left[0]*t - 0.18983879552606) - 0.9818152737217*(SV_bottom_left[1]*t + 0.9818152737217) + 0*(SV_bottom_left[2]*t - 0), t)
#print(t1)
bottom_left_corner = SV_bottom_left * t1

SV_adj_bottom_left = np.array([0.29765212097465, -0.94132008519464, 0.15912168956009])
t2 = solve(0.18983879552606*(SV_adj_bottom_left[0]*t - 0.18983879552606) - 0.9818152737217*(SV_adj_bottom_left[1]*t + 0.9818152737217) + 0*(SV_adj_bottom_left[2]*t - 0), t)
#print(t2)
adj_bottom_left_corner = SV_adj_bottom_left * t2

SV_up_adj_bottom_left = np.array([0.29756555627888, -0.94134709255416, 0.15912382303183])
t3 = solve(0.18983879552606*(SV_up_adj_bottom_left[0]*t - 0.18983879552606) - 0.9818152737217*(SV_up_adj_bottom_left[1]*t + 0.9818152737217) + 0*(SV_up_adj_bottom_left[2]*t - 0), t)
#print(t3)
up_adj_bottom_left_corner = SV_up_adj_bottom_left * t3

SV_down_adj_bottom_left = np.array([0.29769976737546, -0.94132038358211, 0.15903076418551])
t4 = solve(0.18983879552606*(SV_down_adj_bottom_left[0]*t - 0.18983879552606) - 0.9818152737217*(SV_down_adj_bottom_left[1]*t + 0.9818152737217) + 0*(SV_down_adj_bottom_left[2]*t - 0), t)
#print(t4)
down_adj_bottom_left_corner = SV_down_adj_bottom_left * t4

first_diag = []
up_right_interval = up_adj_bottom_left_corner - bottom_left_corner
for i in range(8):
    first_diag.append(bottom_left_corner + up_right_interval*i)
diag_1 = np.array(first_diag)

up_diag_interval = adj_bottom_left_corner - bottom_left_corner
diag_2 = diag_1[:-1] + up_diag_interval

right_interval = down_adj_bottom_left_corner - diag_2[0]

diags = [diag_1, diag_2]
for i in range(13):
    if i % 2 == 0:
        diags.append(diags[i+1] + right_interval)
    else:
        diags.append(diags[i+1][:-1] + up_diag_interval)

min_dot_cord = [0, 0]
min_dot = 10
for i in range(len(diags)):
    diags[i] = diags[i].astype(float)
    for j in range(len(diags[i])):
        current_dot = abs(1 - np.dot(target_vector, diags[i][j] / np.linalg.norm(diags[i][j])))
        #print(diags[i][j] / np.linalg.norm(diags[i][j]))
        if current_dot < min_dot:
            min_dot = current_dot
            min_dot_cord = (i, j)
print(min_dot_cord)
print(diags[min_dot_cord[0]][min_dot_cord[1]] / np.linalg.norm(diags[min_dot_cord[0]][min_dot_cord[1]]))
print(min_dot)

(8, 3)
[ 0.29734934 -0.94156582  0.15823142]
1.500060742287701e-09


In [7]:
# Glyph 5/7

t = Symbol('t')
SV_bottom_left = np.array([0.29738342144354, -0.9415419889134, 0.15830913986102])
t1 = solve(0.18983879552606*(SV_bottom_left[0]*t - 0.18983879552606) - 0.9818152737217*(SV_bottom_left[1]*t + 0.9818152737217) + 0*(SV_bottom_left[2]*t - 0), t)
#print(t1)
bottom_left_corner = SV_bottom_left * t1

SV_adj_bottom_left = np.array([0.29737855217021, -0.94154539389862, 0.15829803516608])
t2 = solve(0.18983879552606*(SV_adj_bottom_left[0]*t - 0.18983879552606) - 0.9818152737217*(SV_adj_bottom_left[1]*t + 0.9818152737217) + 0*(SV_adj_bottom_left[2]*t - 0), t)
#print(t2)
adj_bottom_left_corner = SV_adj_bottom_left * t2

SV_up_adj_bottom_left = np.array([0.29736772835357, -0.9415487679036, 0.15829830003211])
t3 = solve(0.18983879552606*(SV_up_adj_bottom_left[0]*t - 0.18983879552606) - 0.9818152737217*(SV_up_adj_bottom_left[1]*t + 0.9818152737217) + 0*(SV_up_adj_bottom_left[2]*t - 0), t)
#print(t3)
up_adj_bottom_left_corner = SV_up_adj_bottom_left * t3

SV_down_adj_bottom_left = np.array([0.29738450662114, -0.94154542468084, 0.15828666552898])
t4 = solve(0.18983879552606*(SV_down_adj_bottom_left[0]*t - 0.18983879552606) - 0.9818152737217*(SV_down_adj_bottom_left[1]*t + 0.9818152737217) + 0*(SV_down_adj_bottom_left[2]*t - 0), t)
#print(t4)
down_adj_bottom_left_corner = SV_down_adj_bottom_left * t4

first_diag = []
up_right_interval = up_adj_bottom_left_corner - bottom_left_corner
for i in range(8):
    first_diag.append(bottom_left_corner + up_right_interval*i)
diag_1 = np.array(first_diag)

up_diag_interval = adj_bottom_left_corner - bottom_left_corner
diag_2 = diag_1[:-1] + up_diag_interval

right_interval = down_adj_bottom_left_corner - diag_2[0]

diags = [diag_1, diag_2]
for i in range(13):
    if i % 2 == 0:
        diags.append(diags[i+1] + right_interval)
    else:
        diags.append(diags[i+1][:-1] + up_diag_interval)

min_dot_cord = [0, 0]
min_dot = 10
for i in range(len(diags)):
    diags[i] = diags[i].astype(float)
    for j in range(len(diags[i])):
        current_dot = abs(1 - np.dot(target_vector, diags[i][j] / np.linalg.norm(diags[i][j])))
        #print(diags[i][j] / np.linalg.norm(diags[i][j]))
        if current_dot < min_dot:
            min_dot = current_dot
            min_dot_cord = (i, j)
print(min_dot_cord)
print(diags[min_dot_cord[0]][min_dot_cord[1]] / np.linalg.norm(diags[min_dot_cord[0]][min_dot_cord[1]]))
print(min_dot)

(2, 1)
[ 0.29736881 -0.9415522   0.15827583]
1.7085333148258997e-11


In [8]:
# Glyph 6/7

t = Symbol('t')
SV_bottom_left = np.array([0.29737307415036, -0.94154922435014, 0.15828554228361])
t1 = solve(0.18983879552606*(SV_bottom_left[0]*t - 0.18983879552606) - 0.9818152737217*(SV_bottom_left[1]*t + 0.9818152737217) + 0*(SV_bottom_left[2]*t - 0), t)
#print(t1)
bottom_left_corner = SV_bottom_left * t1

SV_adj_bottom_left = np.array([0.29737246547578, -0.94154964994561, 0.15828415417897])
t2 = solve(0.18983879552606*(SV_adj_bottom_left[0]*t - 0.18983879552606) - 0.9818152737217*(SV_adj_bottom_left[1]*t + 0.9818152737217) + 0*(SV_adj_bottom_left[2]*t - 0), t)
#print(t2)
adj_bottom_left_corner = SV_adj_bottom_left * t2

SV_up_adj_bottom_left = np.array([0.29737111249415, -0.94155007169552, 0.15828418728399])
t3 = solve(0.18983879552606*(SV_up_adj_bottom_left[0]*t - 0.18983879552606) - 0.9818152737217*(SV_up_adj_bottom_left[1]*t + 0.9818152737217) + 0*(SV_up_adj_bottom_left[2]*t - 0), t)
#print(t3)
up_adj_bottom_left_corner = SV_up_adj_bottom_left * t3

SV_down_adj_bottom_left = np.array([0.29737320978138, -0.94154965378808, 0.15828273296814])
t4 = solve(0.18983879552606*(SV_down_adj_bottom_left[0]*t - 0.18983879552606) - 0.9818152737217*(SV_down_adj_bottom_left[1]*t + 0.9818152737217) + 0*(SV_down_adj_bottom_left[2]*t - 0), t)
#print(t4)
down_adj_bottom_left_corner = SV_down_adj_bottom_left * t4

first_diag = []
up_right_interval = up_adj_bottom_left_corner - bottom_left_corner
for i in range(8):
    first_diag.append(bottom_left_corner + up_right_interval*i)
diag_1 = np.array(first_diag)

up_diag_interval = adj_bottom_left_corner - bottom_left_corner
diag_2 = diag_1[:-1] + up_diag_interval

right_interval = down_adj_bottom_left_corner - diag_2[0]

diags = [diag_1, diag_2]
for i in range(13):
    if i % 2 == 0:
        diags.append(diags[i+1] + right_interval)
    else:
        diags.append(diags[i+1][:-1] + up_diag_interval)

min_dot_cord = [0, 0]
min_dot = 10
for i in range(len(diags)):
    diags[i] = diags[i].astype(float)
    for j in range(len(diags[i])):
        current_dot = abs(1 - np.dot(target_vector, diags[i][j] / np.linalg.norm(diags[i][j])))
        #print(diags[i][j] / np.linalg.norm(diags[i][j]))
        if current_dot < min_dot:
            min_dot = current_dot
            min_dot_cord = (i, j)
print(min_dot_cord)
print(diags[min_dot_cord[0]][min_dot_cord[1]] / np.linalg.norm(diags[min_dot_cord[0]][min_dot_cord[1]]))
print(min_dot)

(6, 0)
[ 0.29737348 -0.94155051  0.15827711]
3.8402614421784165e-13


In [9]:
# Glyph 7/7

t = Symbol('t')
SV_bottom_left = np.array([0.29737401362962, -0.94155014025356, 0.15827832892193])
t1 = solve(0.18983879552606*(SV_bottom_left[0]*t - 0.18983879552606) - 0.9818152737217*(SV_bottom_left[1]*t + 0.9818152737217) + 0*(SV_bottom_left[2]*t - 0), t)
#print(t1)
bottom_left_corner = SV_bottom_left * t1

SV_adj_bottom_left = np.array([0.29737393754495, -0.94155019345204, 0.15827815540825])
t2 = solve(0.18983879552606*(SV_adj_bottom_left[0]*t - 0.18983879552606) - 0.9818152737217*(SV_adj_bottom_left[1]*t + 0.9818152737217) + 0*(SV_adj_bottom_left[2]*t - 0), t)
#print(t2)
adj_bottom_left_corner = SV_adj_bottom_left * t2

SV_up_adj_bottom_left = np.array([0.29737376842229, -0.94155024617116, 0.15827815954627])
t3 = solve(0.18983879552606*(SV_up_adj_bottom_left[0]*t - 0.18983879552606) - 0.9818152737217*(SV_up_adj_bottom_left[1]*t + 0.9818152737217) + 0*(SV_up_adj_bottom_left[2]*t - 0), t)
#print(t3)
up_adj_bottom_left_corner = SV_up_adj_bottom_left * t3

SV_down_adj_bottom_left = np.array([0.29737403058292, -0.94155019393136, 0.15827797775651])
t4 = solve(0.18983879552606*(SV_down_adj_bottom_left[0]*t - 0.18983879552606) - 0.9818152737217*(SV_down_adj_bottom_left[1]*t + 0.9818152737217) + 0*(SV_down_adj_bottom_left[2]*t - 0), t)
#print(t4)
down_adj_bottom_left_corner = SV_down_adj_bottom_left * t4

first_diag = []
up_right_interval = up_adj_bottom_left_corner - bottom_left_corner
for i in range(8):
    first_diag.append(bottom_left_corner + up_right_interval*i)
diag_1 = np.array(first_diag)

up_diag_interval = adj_bottom_left_corner - bottom_left_corner
diag_2 = diag_1[:-1] + up_diag_interval

right_interval = down_adj_bottom_left_corner - diag_2[0]

diags = [diag_1, diag_2]
for i in range(13):
    if i % 2 == 0:
        diags.append(diags[i+1] + right_interval)
    else:
        diags.append(diags[i+1][:-1] + up_diag_interval)

min_dot_cord = [0, 0]
min_dot = 10
for i in range(len(diags)):
    diags[i] = diags[i].astype(float)
    for j in range(len(diags[i])):
        current_dot = abs(1 - np.dot(target_vector, diags[i][j] / np.linalg.norm(diags[i][j])))
        #print(diags[i][j] / np.linalg.norm(diags[i][j]))
        if current_dot < min_dot:
            min_dot = current_dot
            min_dot_cord = (i, j)
print(min_dot_cord)
print(diags[min_dot_cord[0]][min_dot_cord[1]] / np.linalg.norm(diags[min_dot_cord[0]][min_dot_cord[1]]))
print(min_dot)

(3, 0)
[ 0.29737395 -0.94155025  0.1582778 ]
1.5543122344752192e-15


In [32]:
print(np.dot(target_vector, [0.18983879552606, -0.9818152737217, 0]))
print(np.dot(target_vector, [0.39831700267993, -0.85296865578697, 0.3373248250886]))
#print(np.dot(target_vector, np.array([0.32750377614459, -0.92692341833681, 0.1831782005312])))
print(np.array([0.31135363, -0.95831709,  0.17362526] / np.linalg.norm([0.31135363, -0.95831709,  0.17362526])))
print(target_vector)
0.29737404753619, -0.94155024760905, 0.15827762659103

0.9808815269512343
0.9749529835126061
[ 0.30450929 -0.93725085  0.16980854]
[ 0.29737395 -0.94155025  0.1582778 ]
